platform :ios, '13.0'

use_frameworks!
project 'StockInfo.xcodeproj'

target 'StockInfo' do
  pod 'SwiftYFinance', :path => '../'
  target 'StockInfoTests' do
    pod 'SwiftYFinance', :path => '../'
  end
end
